name: CI

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run solhint
        uses: solidity/actions/solhint@v1.0.1
        with:
          args: .

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - run: yarn ganache -d > /dev/null &
      - run: yarn test
