name: CI

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Run solhint
        run: npx solhint .

      - name: Start Ganache
        run: |
          yarn global add ganache-cli
          yarn ganache -d > /dev/null &
        shell: bash

      - name: Run tests
        run: yarn test
